using System;
using System.Collections.Generic;
using System.IO.Abstractions;
using System.Linq;
using System.Text;
using Skeleton.OpenApi;
using Skeleton.ProjectGeneration;
using Skeleton.Model;
using Skeleton.Templating.Classes;
using Skeleton.Templating.DatabaseFunctions;
using Skeleton.Templating.ReactClient;
using Skeleton.Templating.TestData;
using Serilog;

namespace Skeleton.Console
{
    public class Generator
    {
        private readonly IFileSystem _fs;
        private readonly Settings _settings;
        private readonly FileWriter _fileWriter;

        private const string DbScriptsRelativePath = ".\\Database\\Domain\\";

        public Generator(IFileSystem fileSystem, Settings settings, FileWriter fileWriter)
        {
            _fs = fileSystem;
            _settings = settings;
            _fileWriter = fileWriter;
        }

        private string DatabaseScriptsFolder => _fs.Path.Combine(CSharpDataAccessFolder, DbScriptsRelativePath);

        private string CSharpDataAccessFolder
        {
            get
            {
                if (!string.IsNullOrEmpty(_settings.DataDirectory))
                {
                    return _fs.Path.Combine(_settings.RootDirectory, _settings.DataDirectory);
                }
                
                return _fs.Path.Combine(_settings.RootDirectory, "Data");
            }
        }
        
        private string CSharpDataAccessTestFolder
        {
            get
            {
                if (!string.IsNullOrEmpty(_settings.TestDataDirectory))
                {
                    return _fs.Path.Combine(_settings.RootDirectory, _settings.TestDataDirectory);
                }
                
                return _fs.Path.Combine(_settings.RootDirectory, "Data\\Test");
            }
        }

        public void Generate(ITypeProvider typeProvider)
        {
            Log.Information("Starting Code Generation in {RootDirectory}", _settings.RootDirectory);
            
            if (_settings.AddGeneratedOptionsToDatabase)
            {
                var sb = new StringBuilder();
                sb.AppendLine("-- generated by a tool");
                typeProvider.DropGeneratedOperations(_settings, sb);
                typeProvider.DropGeneratedTypes(_settings, sb);
                var dropFile = new CodeFile() {Contents = sb.ToString(), Name = "drop_generated.sql"};
                _fileWriter.ApplyCodeFiles(new List<CodeFile>{dropFile}, DatabaseScriptsFolder);
                Log.Information("Finishing dropping generated operations");
            }

            var domain = typeProvider.GetDomain(_settings);
            Log.Information("Finished building domain");

            SetupRootFolder();

            GenerateDbFunctions(domain, _settings.AddGeneratedOptionsToDatabase, typeProvider);
            Log.Information("Finished generating db functions");

            typeProvider.GetOperations(domain);
            Log.Information("Finished adding operations to domain");

            SanityCheckDomain(domain);

            GenerateClasses(domain);
            Log.Information("Finished generating classes");

            GenerateRepositories(domain);
            Log.Information("Finished generating repositories");

            if (_settings.GenerateTestRepos && !string.IsNullOrEmpty(_settings.TestDataDirectory))
            {
                // this is very much a work-in-progress
                GenerateTestRepositories(domain);
                Log.Information("Finished generating test repositories");
            }
            
            if (domain.ResultTypes.Any(rt => !rt.Ignore))
            {
                GenerateReturnTypes(domain);
                Log.Information("Finished generating return types");
            }
            
            if (_settings.WebUIType == WebUIType.React)
            {
                GenerateWebApi(domain);
                GenerateWebApiModels(domain);
                
                if (!string.IsNullOrEmpty(_settings.OpenApiUri))
                {
                    var openApiDocProvider = new OpenApiDocumentProvider(_fs, _settings);
                    var openApiDomainProvider = new OpenApiDomainProvider(openApiDocProvider);
                    openApiDomainProvider.AugmentDomainFromOpenApi(domain);
                }
                
                GenerateClientServiceProxy(domain);
                GenerateClientApiModels(domain);
                GenerateClientPages(domain);
                Log.Information("Finished generating react UI");
            }

            if (_settings.ClientAppTypes.Contains(ClientAppUIType.Flutter))
            {
                var flutterGen = new Flutter.Generator(_fs, _settings);
                var flutterFiles = flutterGen.Generate(domain);
                _fileWriter.ApplyCodeFiles(flutterFiles, flutterGen.FlutterRootFolder);
                Log.Information("Finished generating flutter UI");
            }

            if (_settings.TestDataSize != null && _settings.TestDataSize > 0)
            {
                var testDataGen = new TestDataGenerator();
                var testData = testDataGen.Generate(domain);
                if (testData.Any())
                {
                    typeProvider.AddTestData(testData);
                }
            }
            
            Log.Information("Finished Code Generation");
        }

        private void FilterDomainToSingleType(Domain domain)
        {
            var selectedType = domain.Types.FirstOrDefault(t => t.Name == _settings.TypeName);
            if (selectedType == null)
            {
                throw new InvalidOperationException("Unable to find the type you specified to operate on " +
                                                    _settings.TypeName);
            }

            domain.Types.Clear();
            domain.Types.Add(selectedType);
            var ops = domain.Operations.Where(o =>
                o.Attributes?.applicationtype == selectedType.Name || o.Returns.SimpleReturnType == selectedType);
            domain.Operations.Clear();
            domain.Operations.AddRange(ops);
        }

        private void SetupRootFolder()
        {
            if (!_fs.Directory.Exists(_settings.RootDirectory))
            {
                _fs.Directory.CreateDirectory(_settings.RootDirectory);
            }
        }

        private void GenerateClasses(Domain domain)
        {
            var generator = new ClassGenerator();
            var files = generator.GenerateDomain(domain);
            const string DomainObjectFolderName = "Domain";
            var dir = _fs.Path.Combine(CSharpDataAccessFolder, DomainObjectFolderName);
            _fileWriter.ApplyCodeFiles(files, dir);
        }

        private void GenerateReturnTypes(Domain domain)
        {
            var generator = new ClassGenerator();
            var files = generator.GenerateReturnTypes(domain);
            const string folderName = "Model";
            var dir = _fs.Path.Combine(CSharpDataAccessFolder, folderName);
            _fileWriter.ApplyCodeFiles(files, dir);
        }

        private void GenerateDbFunctions(Domain domain, bool addGeneratedOperationsToDatabase, ITypeProvider typeProvider)
        {
            var generator = new DbFunctionGenerator();
            var files = generator.Generate(domain, _settings);

            _fileWriter.ApplyCodeFiles(files, DatabaseScriptsFolder, file =>
            {
                if (addGeneratedOperationsToDatabase)
                {
                    typeProvider.AddGeneratedOperation(file.Contents);
                }
            });
        }

        private void GenerateRepositories(Domain domain)
        {
            var generator = new ClassGenerator();
            var files = generator.GenerateRepositories(domain);

            var infra = generator.GenerateRepositoryInfrastructure(domain);
            files.AddRange(infra);

            const string RepoFolderName = "Repository";
            var path = _fs.Path.Combine(CSharpDataAccessFolder, RepoFolderName);

            _fileWriter.ApplyCodeFiles(files, path);
        }
        
        private void GenerateTestRepositories(Domain domain)
        {
            var generator = new ClassGenerator();
            var files = generator.GenerateTestRepositories(domain);
            
            const string RepoFolderName = "Repository";
            var path = _fs.Path.Combine(CSharpDataAccessTestFolder, RepoFolderName);

            _fileWriter.ApplyCodeFiles(files, path);
        }

        private void GenerateWebApi(Domain domain)
        {
            var generator = new ClassGenerator();
            var files = generator.GenerateWebApiControllers(domain);
            _fileWriter.ApplyCodeFiles(files, "Controllers");
        }

        private void GenerateWebApiModels(Domain domain)
        {
            var generator = new ClassGenerator();
            var files = generator.GenerateWebApiModels(domain);
            _fileWriter.ApplyCodeFiles(files, "Models");
        }
        
        private void GenerateViewModels(Domain domain)
        {
            var generator = new ClassGenerator();
            var files = generator.GenerateEditModels(domain);

            _fileWriter.ApplyCodeFiles(files, "Models");
        }
        
        private void GenerateClientServiceProxy(Domain domain)
        {
            var clientGenerator = new ReactClientGenerator();
            var files = clientGenerator.Generate(domain);
            _fileWriter.ApplyCodeFiles(files, _settings.ResolveClientAppDirectory());
        }

        private void GenerateClientApiModels(Domain domain)
        {
            var clientGenerator = new ReactClientGenerator();
            var files = clientGenerator.GenerateClientModels(domain);
            _fileWriter.ApplyCodeFiles(files, _settings.ResolveClientAppDirectory());
        }

        private void GenerateClientPages(Domain domain)
        {
            var generator = new ReactClientGenerator();
            var listPages = generator.GenerateComponents(domain);
            _fileWriter.ApplyCodeFiles(listPages, _settings.ResolveClientAppDirectory());
        }

        private void SanityCheckDomain(Domain domain)
        {
            if (domain.Types.Count == 0)
            {
                Log.Error("There are no types in domain");
            }

            if (domain.Operations.Count == 0)
            {
                Log.Error("There are no operations in domain");
            }

            foreach (var applicationType in domain.FilteredTypes)
            {
                if (applicationType.Fields.Count == 0)
                {
                    Log.Warning("Type {ApplicationType} has no fields", applicationType.Name);
                }

                if (applicationType.Fields.Any(f => string.IsNullOrEmpty(f.Name)))
                {
                    Log.Warning("Type {ApplicationType} has a field with no name", applicationType.Name);
                }

                if (string.IsNullOrEmpty(applicationType.Namespace))
                {
                    Log.Warning("Type {ApplicationType} has no namespace", applicationType.Name);
                }

                if (!applicationType.Ignore)
                {
                    var operations = domain.Operations.Where(o => o.Returns.SimpleReturnType == applicationType);
                    if (operations.Count() == 0)
                    {
                        Log.Warning("Type {ApplicationType} is not returned by any operations", applicationType.Name);
                    }
                }
            }

            foreach (var resultType in domain.ResultTypes)
            {
                if (resultType.Fields.Count == 0)
                {
                    Log.Warning("Result type {ResultType} has no fields", resultType.Name);
                }
                
                if (resultType.Fields.Any(f => string.IsNullOrEmpty(f.Name)))
                {
                    Log.Warning("Result type {ResultType} has a field with no name", resultType.Name);
                }

                var operations = domain.Operations.Where(o => o.Returns.SimpleReturnType == resultType);
                var parameters = domain.Operations.SelectMany(o => o.Parameters).Where(p =>
                    p.ClrType == typeof(ResultType) && p.ProviderTypeName == resultType.Name);
                if (operations.Count() == 0 && parameters.Count() == 0)
                {
                    Log.Warning("Result Type {ResultType} is not returned by, or used as a parameter in any operations", resultType.Name);
                }
            }

            foreach (var op in domain.Operations)
            {
                if (op.Returns == null)
                {
                    Log.Warning("Operation {OperationName} does not return anything", op.Name);
                }

                if (op.Parameters.Any(p => string.IsNullOrEmpty(p.Name)))
                {
                    Log.Warning("Operation {OperationName} has a parameter with no name", op.Name);
                }
            }
        }
    }
}
